spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # SQL 개행
        highlight_sql: true
        use_sql_comments: true # 실행되는 쿼리문 HINT 표시
    database-platform: org.hibernate.dialect.H2Dialect
  devtools:
    livereload:
      enabled: true